### ISSUE TITLE
is it can be?

### ISSUE THREAD

**Issue by sauio** [nickcharlton/dotfiles#25]
Hi, is it possible to do script for this settings? i search hard bud cant find

1. "Finder: items in the sidebar"
```
show Mac
hide iCloud/recents
defaults write com.apple.finder ShowRecentTags -bool false
```

2. "Settings-general-RecentItems - NONE"

3. "set F13(printScr) for save-screenshot-as-file"

4. "set Alt+F13(printScr) for save-pic-of-area-as-file"

5. "Mojave Settings-Update -ALL disable"

**Comment by nickcharlton** [comment]
I'm not really sure. I'd recommend investigating the following as you might find what you're looking for there:

1. https://www.defaults-write.com
2. https://github.com/mathiasbynens/dotfiles/blob/master/.macos
